### ISSUE TITLE
Demo site has been down

### ISSUE THREAD

**Issue by draco1023** [skishore/makemeahanzi#11]

**Comment by skishore** [comment]
Thanks for reporting the issue. I disabled my hosting recently after it got more expensive - the site wasn't getting very much traffic, so I couldn't justify keeping it up. I'll look for a new provider.

In the meantime, please take a look at https://skishore.github.io/inkstone/ if you're interested. I think it's a much more effective demo of this dataset than what I had before!

**Comment by skishore** [comment]
And it's up at https://makemeahanzi.herokuapp.com. Heroku is amazing!
