### ISSUE TITLE
How should I cite this work?

### ISSUE THREAD

**Issue by Xiaofeng-Guo** [skishore/makemeahanzi#118]
Hi, this is a great work and we want to cite this work in our paper. Could you provide a citation bibtex file or what is the correct way for us to cite this work? Thank you!

**Comment by skishore** [comment]
Sorry for the late response. You can cite it in APA format as:

Kishore, Shaunak (2018). Make Me a Hanzi (commit 618dbab). GitHub link: https://github.com/skishore/makemeahanzi

Please also cite the two Arphic Technology fonts from which this work is derived: Arphic PL KaitiM GB and Arphic PL UKai.

If you use the same format for those fonts, they'd be:

Arphic Technology Co., Ltd (1999). Arphic PL KaitiM GB. Retrieved from: ...
Arphic Technology Co., Ltd (1999). Arphic PL UKai. Retrieved from: ...

I have copies of those fonts saved under https://github.com/skishore/makemeahanzi/tree/tool/public/arphic, but there may be a more canonical link to retrieve them from (e.g. some Linux distribution).

**Comment by skishore** [comment]
Here, the Debian distribution of these fonts looks like a good stable link:

https://packages.debian.org/stable/fonts/fonts-arphic-gkai00mp
https://packages.debian.org/stable/fonts/fonts-arphic-ukai
