### ISSUE TITLE
incorrect pronunciation for 耶

### ISSUE THREAD

**Issue by webmagnets** [skishore/makemeahanzi#17]
I'm sorry I can't fix it myself. I don't know how to do a pull request.

The correct pronuncation for "耶" is "yē", not "yé".

**Comment by laughedelic** [comment]
CCEDict lists 3 variants of 耶:
* yē	(phonetic ye)
* yé	interrogative particle (classical)
* ye	final particle indicating enthusiasm etc

**Comment by skishore** [comment]
I'm closing this issue, since I don't aim for near-perfect accuracy with character metadata - this project is focused on stroke order and related graphical data.
