### ISSUE TITLE
japanese characters

### ISSUE THREAD

**Issue by parsimonhi** [skishore/makemeahanzi#18]
I made a derived project from makemeahanzi called animCJK (https://github.com/parsimonhi/animCJK). It contains svg files for the 2136 "jōyō kanji" in use in Japan and the 3500 "frequently used simplified hanzi".

Svg files of animCJK are completely different from svg files of makemeahanzi. However i made two files (graphicsJa.txt and graphicsZhHans.txt) that have the same format as your graphics.txt. So you can import what was changed very easily if you wish it.

Note that many characters (about one third) are not the same in Japanese and in Chinese even when they share the same unicode (different stroke order, different stroke direction, different glyph, ...).  So don't merge the two files without care.

Note also that i recomputed all medians in order to be sure that a stroke-width of 128 is sufficient to cover all stroke shapes.

Hope it helps.

**Comment by skishore** [comment]
Hey, that's really cool! Did you automate the process of changing the
Chinese stroke order graphics into the Japanese ones? I'm curious what
approach you took to do that.

I've gotten quite a few requests for versions of the Make Me a Hanzi data
for Japanese language learners. I will be sure to forward them to your site!

**Comment by parsimonhi** [comment]
I did it manually one by one using a text editor to modify directly the svg files (just to invert some paths, i.e. some lines of text: not very difficult and not so long). It is difficult (but not impossible) to automate the process because there are many different cases. As a result, identifying what kind of correction had to be done was the most time consuming. Anyway, the most difficult was not to correct stroke orders, but to correct glyphs and to create characters that were not defined at all in makemeahanzi (roughly 30% of the corrections were made for modifying stroke orders, 30% were made for modifying glyphs, 30% were made for creating new characters and 10% were made for other cases). To correct glyphs or to create new characters, most of the time, there was no better way than modifying the svg using a graphic editor (I used inkscape).

**Comment by skishore** [comment]
Huh, interesting! So for the characters that you had to create from
scratch, how did you split the font's glyph into strokes? Do you have an
example of one of those that you could show me on the demo page? I wrote
this tool that did most of that for me, so it would be interesting to
compare notes.

**Comment by parsimonhi** [comment]
I didn't get the new character strokes from a font glyph since these characters are not defined in the Arphic fonts, and trying another font doesn't work well (too much work to transform a glyph of another font into a glyph that is  Arphic font like).

So, i build the new characters one by one in two steps:

- Step 1: using a text editor, i collected svg stroke paths from similar svg components of other characters already defined (in makemeahanzi or in animCJK).

- Step 2: using inkspace,  i adapted the svg paths to produce a new svg that has an Arphic font look. Most of the time, it was just a question of translating some nodes of the Bezier curves that defined the stroke shapes and/or scaling these shapes.

On http://gooo.free.fr/animCJK/all.php, take a look at the character lists. All the characters in green are those that i created. All the characters in blue are those that i modified. All the characters in red are those that i have not created yet.

**Comment by parsimonhi** [comment]
For instance, i just created 崚. I got the left part from 嶼 and the right part from 绫. In this case, no need to use inkspace because the original components have roughly the right size.

**Comment by skishore** [comment]
I see, very cool! You've basically created a new font with all those new
characters!

I think the Arphic ukai font might have had quite a few of those characters
in it. I just stopped building the stroke order graphics after doing the
most common Chinese characters.

**Comment by parsimonhi** [comment]
I missed this point. Thank you for mentioning.

I found 15 Jōyō kanji in Arphic font that are not in makemeahanzi. Not a huge number, but it helps.

**Comment by skishore** [comment]
Since other people have also asked about non-PRC stroke order data, I've linked to your site and KanjiVG from the readme.

**Comment by parsimonhi** [comment]
Thanks for the link!
