### ISSUE TITLE
Wrong stroke orders for a traditional character

### ISSUE THREAD

**Issue by GrimReaperSam** [skishore/makemeahanzi#19]
Hey,

The program has an issue when writing 候 (traditional character). It writes the leftmost two strokes, then goes to the righttopmost 2 strokes, then the vertical line, then continues normally. I know you have a place where you can correct individiual character but I'm not sure how to do that. Could you correct it or guide me perhaps?

Thanks!

**Comment by skishore** [comment]
Thanks for the report. It's fixed here, and I'm pulling the fix into Inkstone now.

**Comment by GrimReaperSam** [comment]
That's awesome thank you! While you're at it I found out today that this character is also drawn weirdly 餃.
However, I'm not sure what is the correct way so do you mind checking?

Cheers!

**Comment by skishore** [comment]
I'm looking at that character here: http://makemeahanzi.herokuapp.com/#/codepoint/39171

Are you referring to the way the 食 radical is written with one stroke at the end instead of two? That is a bit of an irregularity, but it's part of the open-source Arphic font that Make Me a Hanzi is based off of and I don't have a great way to edit it. There are many other characters with similar issues, particularly traditional ones.

**Comment by GrimReaperSam** [comment]
Sorry!! I meant this one: 條.
I must've copied the wrong character up there.

**Comment by skishore** [comment]
I see! Yeah, there are two oddities with that character. First off, that "tiao" component on the right is written the traditional way. That's an artifact of the Arphic font, and difficult to fix. The direction of one of the strokes in that component is also wrong, which I've fixed in 6104c89887ecd22f4bbeabbb46de9a1a63185bd1. Thanks!

**Comment by GrimReaperSam** [comment]
Hi,

I have a couple more characters that have weird stroke order or don't respond correctly (favoring a stroke over another).

飛 ： Doesn't recognize strokes correctly in the upper part (mixes the stroke when drawing 飞)
飯 ： Wrong stroke order for the right part (first stroke of 反)
盤 ： Doesn't recognize strokes for top right part (very hard to draw the second stroke of 几)
覺 ： first x on top wrong order, compare to 學

Thanks again for the amazing work you're doing. If I knew how to update it i'll do it myself.

**Comment by skishore** [comment]
Fixed the data for 飯 and 覺. The data for the other two is correct but the handwriting recognition algorithm could be improved, so I filed the other issue.

**Comment by GrimReaperSam** [comment]
Hey,

Thanks, I'm waiting for the inkstone update!
If you don't mind I found a bit more inconsistencies.

對: weird stroke order with homework 作業  (Talking about the top left part)
髒: weird order for the grass character on the right
醫: top right is hard to write, guess same problem as 盤.
黑 and 點: The stroke order doesn't feel correct (maybe different between them?)

Thanks man

**Comment by skishore** [comment]
I don't see what is wrong with 對.

Fixed 髒.

That's right about 醫 - I will fix it all in one go by improving recognition for that "shu1" component. The algorithm makes use of decompositions so addressing it at that level will fix it for all characters.

Wow, you're right about 黑, and it affects a few dozen characters! However, I am not sure what the correct order is - there is conflicting information on the internet. Do you happen to have a reference for (mainland Chinese) stroke order which we could use to disambiguate?

**Comment by GrimReaperSam** [comment]
I'll check the first one later. Maybe I'm just confused about it.

For 黑，you might be able to check drawings on https://www.yellowbridge.com/chinese/dictionary.php.
I can always ask chinese or taiwanese friends about how they write it. However they don't have the same order.

**Comment by skishore** [comment]
I've checked there, Wikipedia, Arch Chinese, and a few other sites. The order from Yellow Bridge seems to be the most common one but since this radical is a part of many characters I want to be sure that I get it right.

**Comment by GrimReaperSam** [comment]
I'll see what I can get once I'm home

**Comment by GrimReaperSam** [comment]
Hi!

Another character that isn't in the dictionary: 鵝, it's used for the word penguin.
Is the inkstone database updated also?

Thanks,
Fayez
