### ISSUE TITLE
Various tiny errors found in 題衆擊搖湧薦混轍韆

### ISSUE THREAD

**Issue by parsimonhi** [skishore/makemeahanzi#20]
Hello,

It seems that some errors are in characters below.

題: wrong stroke order (7th stroke)
衆: wrong stroke order (7th stroke)
擊: wrong stroke order (8th stroke)
搖: wrong stroke order (6th stroke)
湧: wrong stroke order (10th stroke)
薦: wrong stroke direction of the last stroke
混: last stroke is damaged (a tiny line can be seen). One can suppress L 934 105 L 896 112 and modify medians accordingly to clear the problem.
轍: the starting point of 19th stroke median is misplaced.
韆: a very small stroke is drawn at the end of the animation.

Hope it helps!

**Comment by skishore** [comment]
Wow, thanks for all the feedback! I'm taking a look at these now.

**Comment by skishore** [comment]
I didn't see the issue with 衆 - Wikipedia and a few other references agree with the stroke order that I had for that character. All the others are now fixed!

**Comment by parsimonhi** [comment]
In theory 衆 is the Japanese variant of 眾. It seems that the vertical stroke (your 10th stroke) has to be drawn just after your 7th stroke (as in 眾). These 2 strokes (your 7th and 10th strokes) can also be drawn after your 8th and 9th stroke, but i think that the "best" order is 7th-10th-8th-9th. Anyway, there is no good reason to draw the 7th and the 10th strokes with some other strokes between them. Some references: http://www.visualmandarin.com/tools/chinese-stroke-order/65004, https://bihua.51240.com/e8a186__bihuachaxun/, http://kanji.jitenon.jp/kanjib/898.html, http://kanjivg.tagaini.net/viewer.html?kanji=%E8%A1%86

**Comment by skishore** [comment]
I see. Yes, that does look like a mistake. I found six other characters with the same component, so that was a really good catch!
