### ISSUE TITLE
No stroke data for 〇

### ISSUE THREAD

**Issue by hugolpz** [skishore/makemeahanzi#29]
Please don't stone me :laughing: 

But it is considered like a CJK sign for 0 by Wikipedia (right side, bottom of table).
![screenshot from 2018-02-07 16-52-38](https://user-images.githubusercontent.com/1420189/35926190-e0b73b96-0c27-11e8-9f4b-e1c4cb8bc528.png)

So does the [MOOC course](https://www.fun-mooc.fr/courses/Inalco/52004/session1/about) I [code for](http://hanzi.cri-paris.org).

Do we have a source for this sign's stroke order ?
Do we accept the Korean way ?

**Comment by skishore** [comment]
Since this character doesn't appear in the Arphic fonts we're not going to support it here.
