### ISSUE TITLE
Incorrect stroke order for 樂 and 灣

### ISSUE THREAD

**Issue by hanpingchinese** [skishore/makemeahanzi#34]
For these two characters: 樂 and 灣, I believe the central component (i.e. 白 and 言) should come before the components either side. See [here](http://www.eon.com.hk/estroke/).

**Comment by parsimonhi** [comment]
And also 䜌孿巒彎戀攣蠻變鑾鸞

**Comment by skishore** [comment]
That's right, thanks for the catch! The component detection algorithm automatically finds other characters that need to be fixed when I fix one, so in total I found 20 mistakes of this kind.
