### ISSUE TITLE
SVGs are missing paths

### ISSUE THREAD

**Issue by parkin** [skishore/makemeahanzi#35]
In the commit [Update SVGs to use capped strokes](https://github.com/skishore/makemeahanzi/commit/e0089f72b0010413bae0e854cde1c1ceac04f8f8#diff-4e7054b077d096bd2f9c9249169881da), it looks like path data was removed from the svgs. Now, the svg are blank.

Also, it might be helpful to include your script that generates the svg files.

Thanks!

**Comment by skishore** [comment]
Oh no! I know exactly what's wrong, and will have it fixed later tonight.
Thanks for the report!

**Comment by skishore** [comment]
Fixed on latest master. (I amended the broken commit.)

The code to generate the SVGs is a Meteor template on the tool branch:
https://github.com/skishore/makemeahanzi/blob/tool/lib/animation.html
https://github.com/skishore/makemeahanzi/blob/tool/lib/animation.js
