### ISSUE TITLE
Incomplete components: 㳽

### ISSUE THREAD

**Issue by olivernyc** [skishore/makemeahanzi#40]
Hey, I'm trying to correct the stroke order for 爾 (swap fifth and sixth strokes) and I'm running in to a small issue.

I'm able to correct the stroke order, which marks a few downstream characters as incomplete. I'm able to complete all but one, 瀰, which gets stuck on `Incomplete components: 㳽`.

㳽 is not in either font, and I don't think it's part of another character, so I'm not sure how to proceed. Any suggestions?

**Comment by skishore** [comment]
I think the default decomposition for 瀰 is wrong. You'll have to fix it on the analysis stage. Take a look at the current decomposition in dictionary.txt - it's "left-to-right ⿰氵彌", which is correct - the component 㳽 is wrong.

**Comment by skishore** [comment]
Ah, right. I must have made the simplified character a dependency of the traditional one.

For this kind of thing I typically change the code of the relevant stage, let Meteor reload the page, make the edit, then change the code back. It keeps the strictest validation working in general but relaxes it for a small number of characters where the data is wonky. (If I have to keep making the change several times, then I look into a better fix.)

In this case, the relevant line to change is here:
https://github.com/skishore/makemeahanzi/blob/tool/client/lib/analysis.js#L169

Replace it with "this.simplified = null;" to treat the character as if it were simplified already.

**Comment by olivernyc** [comment]
Makes sense -- I got it to work. Thanks again for the help!

**Comment by skishore** [comment]
Fixed by #41
