### ISSUE TITLE
There are stroke error in 袤

### ISSUE THREAD

**Issue by cxy163** [skishore/makemeahanzi#52]
Please check it

**Comment by cxy163** [comment]
“特” is right

**Comment by skishore** [comment]
Yikes, that's way off. I'll fix it in the next batch of edits. Thanks!

**Comment by cxy163** [comment]
I have modify the 袤.svg，but I don't know how to rebuild the median.bin. The brunch tool can't run in my local environment.

<svg version="1.1" viewBox="0 0 1024 1024" xmlns="http://www.w3.org/2000/svg">
  <g stroke="#FFD5D2" stroke-dasharray="1,1" stroke-width="1" transform="scale(4, 4)">
    <line x1="0" y1="0" x2="256" y2="256"></line>
    <line x1="256" y1="0" x2="0" y2="256"></line>
    <line x1="128" y1="0" x2="128" y2="256"></line>
    <line x1="0" y1="128" x2="256" y2="128"></line>
  </g>
  <g transform="scale(1, -1) translate(0, -900)">
    <style type="text/css">
      
        @keyframes keyframes0 {
          from {
            stroke: blue;
            stroke-dashoffset: 391;
            stroke-width: 128;
          }
          56% {
            animation-timing-function: step-end;
            stroke: blue;
            stroke-dashoffset: 0;
            stroke-width: 128;
          }
          to {
            stroke: black;
            stroke-width: 1024;
          }
        }
        #make-me-a-hanzi-animation-0 {
          animation: keyframes0 0.5681966145833334s both;
          animation-delay: 0s;
          animation-timing-function: linear;
        }
      
        @keyframes keyframes1 {
          from {
            stroke: blue;
            stroke-dashoffset: 789;
            stroke-width: 128;
          }
          72% {
            animation-timing-function: step-end;
            stroke: blue;
            stroke-dashoffset: 0;
            stroke-width: 128;
          }
          to {
            stroke: black;
            stroke-width: 1024;
          }
        }
        #make-me-a-hanzi-animation-1 {
          animation: keyframes1 0.89208984375s both;
          animation-delay: 0.5681966145833334s;
          animation-timing-function: linear;
        }
      
        @keyframes keyframes2 {
       from {
            stroke: blue;
            stroke-dashoffset: 604;
            stroke-width: 128;
          }
          66% {
            animation-timing-function: step-end;
            stroke: blue;
            stroke-dashoffset: 0;
            stroke-width: 128;
          }
          to {
            stroke: black;
            stroke-width: 1024;
          }
        }
        #make-me-a-hanzi-animation-2 {
          animation: keyframes2 0.7390950520833334s both;
          animation-delay: 1.4602864583333335s;
          animation-timing-function: linear;
        }
      
        @keyframes keyframes3 {
          from {
            stroke: blue;
            stroke-dashoffset: 567;
            stroke-width: 128;
          }
          65% {
            animation-timing-function: step-end;
            stroke: blue;
            stroke-dashoffset: 0;
            stroke-width: 128;
          }
          to {
            stroke: black;
            stroke-width: 1024;
          }
        }
        #make-me-a-hanzi-animation-3 {
          animation: keyframes3 0.71142578125s both;
          animation-delay: 2.199381510416667s;
          animation-timing-function: linear;
        }
      
        @keyframes keyframes4 {
          from {
            stroke: blue;
            stroke-dashoffset: 509;
            stroke-width: 128;
          }
          62% {
            animation-timing-function: step-end;
            stroke: blue;
            stroke-dashoffset: 0;
            stroke-width: 128;
          }
          to {
            stroke: black;
            stroke-width: 1024;
          }
        }
        #make-me-a-hanzi-animation-4 {
          animation: keyframes4 0.6642252604166666s both;
          animation-delay: 2.910807291666667s;
          animation-timing-function: linear;
        }
      
        @keyframes keyframes5 {
          from {
            stroke: blue;
            stroke-dashoffset: 798;
            stroke-width: 128;
          }
          72% {
            animation-timing-function: step-end;
            stroke: blue;
            stroke-dashoffset: 0;
            stroke-width: 128;
          }
          to {
            stroke: black;
            stroke-width: 1024;
          }
        }
        #make-me-a-hanzi-animation-5 {
          animation: keyframes5 0.8994140625s both;
          animation-delay: 3.5750325520833335s;
          animation-timing-function: linear;
        }
      
        @keyframes keyframes6 {
          from {
            stroke: blue;
            stroke-dashoffset: 604;
            stroke-width: 128;
          }
          66% {
            animation-timing-function: step-end;
            stroke: blue;
            stroke-dashoffset: 0;
            stroke-width: 128;
          }
          to {
            stroke: black;
            stroke-width: 1024;
          }
        }
        #make-me-a-hanzi-animation-6 {
          animation: keyframes6 0.7415364583333334s both;
          animation-delay: 4.474446614583334s;
          animation-timing-function: linear;
        }
      
        @keyframes keyframes7 {
          from {
            stroke: blue;
            stroke-dashoffset: 339;
            stroke-width: 128;
          }
          52% {
            animation-timing-function: step-end;
            stroke: blue;
            stroke-dashoffset: 0;
            stroke-width: 128;
          }
          to {
            stroke: black;
            stroke-width: 1024;
          }
        }
        #make-me-a-hanzi-animation-7 {
          animation: keyframes7 0.52587890625s both;
          animation-delay: 5.215983072916667s;
          animation-timing-function: linear;
        }
      
        @keyframes keyframes8 {
          from {
            stroke: blue;
            stroke-dashoffset: 865;
            stroke-width: 128;
          }
          74% {
            animation-timing-function: step-end;
            stroke: blue;
            stroke-dashoffset: 0;
            stroke-width: 128;
          }
          to {
            stroke: black;
            stroke-width: 1024;
          }
        }
        #make-me-a-hanzi-animation-8 {
          animation: keyframes8 0.9539388020833334s both;
          animation-delay: 5.741861979166667s;
          animation-timing-function: linear;
        }
      
        @keyframes keyframes9 {
          from {
            stroke: blue;
            stroke-dashoffset: 437;
            stroke-width: 128;
          }
          59% {
            animation-timing-function: step-end;
            stroke: blue;
            stroke-dashoffset: 0;
            stroke-width: 128;
          }
          to {
            stroke: black;
            stroke-width: 1024;
          }
        }
        #make-me-a-hanzi-animation-9 {
          animation: keyframes9 0.6056315104166666s both;
          animation-delay: 6.69580078125s;
          animation-timing-function: linear;
        }
      
        @keyframes keyframes10 {
          from {
            stroke: blue;
            stroke-dashoffset: 686;
            stroke-width: 128;
          }
          69% {
            animation-timing-function: step-end;
            stroke: blue;
            stroke-dashoffset: 0;
            stroke-width: 128;
          }
          to {
            stroke: black;
            stroke-width: 1024;
          }
        }
        #make-me-a-hanzi-animation-10 {
          animation: keyframes10 0.8082682291666666s both;
          animation-delay: 7.301432291666667s;
          animation-timing-function: linear;
        }
      
    </style>
    
      <path d="M 467 811 Q 498 789 530 763 Q 543 753 557 755 Q 566 756 569 768 Q 572 781 562 806 Q 550 836 459 852 Q 446 853 440 851 Q 436 847 438 836 Q 442 826 467 811 Z" fill="lightgray"></path>
    
      <path d="M 249 703 Q 222 702 242 684 Q 252 674 266 666 Q 279 657 300 663 Q 525 705 761 725 Q 771 724 780 735 Q 781 745 760 757 Q 729 781 653 758 Q 496 727 249 703 Z" fill="lightgray"></path>
    
      <path d="M 533 501 Q 537 505 528 513 Q 527 514 525 514 C 502 533 491 530 473 506 Q 407 416 227 341 Q 211 334 224 329 Q 255 320 343 355 Q 398 383 437 413 Q 450 423 510 482 L 533 501 Z" fill="lightgray"></path>
    
      <path d="M 336 171 Q 354 129 342 85 Q 338 57 325 42 Q 312 23 319 1 Q 329 -30 344 -42 Q 354 -49 367 -32 Q 397 2 494 82 Q 512 95 514 102 Q 515 115 496 105 Q 462 92 425 76 Q 403 63 393 68 Q 384 74 386 96 Q 390 147 393 160 Q 397 179 384 189 Q 377 196 371 199 C 347 216 325 199 336 171 Z" fill="lightgray"></path>
    
      <path d="M 510 482 Q 529 467 537 441 Q 540 399 525 377 Q 516 358 493 361 Q 471 364 450 366 Q 441 367 445 360 Q 449 354 463 347 Q 494 325 504 308 Q 513 296 524 299 Q 534 300 551 321 Q 581 357 575 425 Q 572 458 564 475 Q 554 493 533 501 C 506 513 488 502 510 482 Z" fill="lightgray"></path>
    
      <path d="M 562 218 Q 535 240 508 265 Q 484 287 461 293 C 433 304 425 285 450 268 Q 490 243 591 142 Q 714 25 753 22 Q 819 22 905 42 Q 939 49 935 58 Q 934 62 900 70 Q 717 106 638 162 Q 607 183 576 207 L 562 218 Z" fill="lightgray"></path>
    
      <path d="M 533 566 Q 602 614 636 621 Q 652 625 647 640 Q 646 653 592 684 Q 576 693 558 687 Q 507 668 431 646 Q 412 639 363 641 Q 344 641 350 625 Q 357 615 372 605 Q 397 592 425 608 Q 540 656 556 649 Q 566 643 562 633 Q 543 608 521 578 C 503 554 508 549 533 566 Z" fill="lightgray"></path>
    
      <path d="M 540 542 Q 541 546 542 550 Q 541 557 533 566 L 521 578 Q 493 594 452 590 Q 445 589 447 581 Q 447 574 454 570 Q 479 554 504 540 Q 507 539 508 537 C 530 516 533 514 540 542 Z" fill="lightgray"></path>
    
      <path d="M 525 514 Q 661 541 698 534 Q 714 530 714 522 Q 714 519 686 463 Q 679 453 685 449 Q 691 445 704 454 Q 750 482 786 491 Q 817 498 816 506 Q 815 515 756 560 Q 735 578 634 557 Q 610 556 540 542 L 508 537 Q 442 530 356 513 Q 307 504 255 498 Q 227 497 245 481 Q 273 459 310 469 Q 398 497 473 506 L 525 514 Z" fill="lightgray"></path>
    
      <path d="M 576 207 Q 577 208 579 208 Q 673 259 720 277 Q 739 280 735 292 Q 731 308 714 330 Q 696 351 674 356 Q 658 357 657 337 Q 657 316 562 218 C 541 196 549 195 576 207 Z" fill="lightgray"></path>
    
      <path d="M 461 293 Q 457 315 429 333 Q 411 343 400 345 Q 391 345 391 333 Q 385 261 245 160 Q 242 160 240 157 Q 200 129 104 79 Q 95 76 104 71 Q 170 64 301 146 Q 307 153 336 171 L 371 199 Q 441 263 450 268 C 466 280 466 280 461 293 Z" fill="lightgray"></path>
    
    
      <clipPath id="make-me-a-hanzi-clip-0">
        <path d="M 467 811 Q 498 789 530 763 Q 543 753 557 755 Q 566 756 569 768 Q 572 781 562 806 Q 550 836 459 852 Q 446 853 440 851 Q 436 847 438 836 Q 442 826 467 811 Z"></path>
      </clipPath>
      <path clip-path="url(#make-me-a-hanzi-clip-0)" d="M 445 843 L 523 805 L 555 769" fill="none" id="make-me-a-hanzi-animation-0" stroke-dasharray="263 526" stroke-linecap="round"></path>
    
      <clipPath id="make-me-a-hanzi-clip-1">
        <path d="M 249 703 Q 222 702 242 684 Q 252 674 266 666 Q 279 657 300 663 Q 525 705 761 725 Q 771 724 780 735 Q 781 745 760 757 Q 729 781 653 758 Q 496 727 249 703 Z"></path>
      </clipPath>
      <path clip-path="url(#make-me-a-hanzi-clip-1)" d="M 243 694 L 290 684 L 688 743 L 728 746 L 770 737" fill="none" id="make-me-a-hanzi-animation-1" stroke-dasharray="661 1322" stroke-linecap="round"></path>
    
      <clipPath id="make-me-a-hanzi-clip-2">
        <path d="M 533 501 Q 537 505 528 513 Q 527 514 525 514 C 502 533 491 530 473 506 Q 407 416 227 341 Q 211 334 224 329 Q 255 320 343 355 Q 398 383 437 413 Q 450 423 510 482 L 533 501 Z"></path>
      </clipPath>
      <path clip-path="url(#make-me-a-hanzi-clip-2)" d="M 523 504 L 485 486 L 420 424 L 371 391 L 290 351 L 229 334" fill="none" id="make-me-a-hanzi-animation-6" stroke-dasharray="473 946" stroke-linecap="round"></path>
    
      <clipPath id="make-me-a-hanzi-clip-3">
        <path d="M 336 171 Q 354 129 342 85 Q 338 57 325 42 Q 312 23 319 1 Q 329 -30 344 -42 Q 354 -49 367 -32 Q 397 2 494 82 Q 512 95 514 102 Q 515 115 496 105 Q 462 92 425 76 Q 403 63 393 68 Q 384 74 386 96 Q 390 147 393 160 Q 397 179 384 189 Q 377 196 371 199 C 347 216 325 199 336 171 Z"></path>
      </clipPath>
      <path clip-path="url(#make-me-a-hanzi-clip-3)" d="M 369 189 L 363 72 L 370 32 L 412 44 L 505 102" fill="none" id="make-me-a-hanzi-animation-8" stroke-dasharray="439 878" stroke-linecap="round"></path>
    
      <clipPath id="make-me-a-hanzi-clip-4">
        <path d="M 510 482 Q 529 467 537 441 Q 540 399 525 377 Q 516 358 493 361 Q 471 364 450 366 Q 441 367 445 360 Q 449 354 463 347 Q 494 325 504 308 Q 513 296 524 299 Q 534 300 551 321 Q 581 357 575 425 Q 572 458 564 475 Q 554 493 533 501 C 506 513 488 502 510 482 Z"></path>
      </clipPath>
      <path clip-path="url(#make-me-a-hanzi-clip-4)" d="M 519 483 L 540 477 L 555 444 L 556 398 L 539 350 L 523 335 L 451 360" fill="none" id="make-me-a-hanzi-animation-5" stroke-dasharray="381 762" stroke-linecap="round"></path>
    
      <clipPath id="make-me-a-hanzi-clip-5">
        <path d="M 562 218 Q 535 240 508 265 Q 484 287 461 293 C 433 304 425 285 450 268 Q 490 243 591 142 Q 714 25 753 22 Q 819 22 905 42 Q 939 49 935 58 Q 934 62 900 70 Q 717 106 638 162 Q 607 183 576 207 L 562 218 Z"></path>
      </clipPath>
      <path clip-path="url(#make-me-a-hanzi-clip-5)" d="M 464 284 L 615 149 L 726 76 L 759 63 L 798 58 L 930 56" fill="none" id="make-me-a-hanzi-animation-10" stroke-dasharray="670 1340" stroke-linecap="round"></path>
    
      <clipPath id="make-me-a-hanzi-clip-6">
        <path d="M 533 566 Q 602 614 636 621 Q 652 625 647 640 Q 646 653 592 684 Q 576 693 558 687 Q 507 668 431 646 Q 412 639 363 641 Q 344 641 350 625 Q 357 615 372 605 Q 397 592 425 608 Q 540 656 556 649 Q 566 643 562 633 Q 543 608 521 578 C 503 554 508 549 533 566 Z"></path>
      </clipPath>
      <path clip-path="url(#make-me-a-hanzi-clip-6)" d="M 359 631 L 401 620 L 432 626 L 519 659 L 573 666 L 596 642 L 537 580 L 530 581" fill="none" id="make-me-a-hanzi-animation-2" stroke-dasharray="476 952" stroke-linecap="round"></path>
    
      <clipPath id="make-me-a-hanzi-clip-7">
        <path d="M 540 542 Q 541 546 542 550 Q 541 557 533 566 L 521 578 Q 493 594 452 590 Q 445 589 447 581 Q 447 574 454 570 Q 479 554 504 540 Q 507 539 508 537 C 530 516 533 514 540 542 Z"></path>
      </clipPath>
      <path clip-path="url(#make-me-a-hanzi-clip-7)" d="M 458 581 L 534 548" fill="none" id="make-me-a-hanzi-animation-3" stroke-dasharray="211 422" stroke-linecap="round"></path>
    
      <clipPath id="make-me-a-hanzi-clip-8">
        <path d="M 525 514 Q 661 541 698 534 Q 714 530 714 522 Q 714 519 686 463 Q 679 453 685 449 Q 691 445 704 454 Q 750 482 786 491 Q 817 498 816 506 Q 815 515 756 560 Q 735 578 634 557 Q 610 556 540 542 L 508 537 Q 442 530 356 513 Q 307 504 255 498 Q 227 497 245 481 Q 273 459 310 469 Q 398 497 473 506 L 525 514 Z"></path>
      </clipPath>
      <path clip-path="url(#make-me-a-hanzi-clip-8)" d="M 248 491 L 268 484 L 300 485 L 416 512 L 671 551 L 732 543 L 750 518 L 690 456" fill="none" id="make-me-a-hanzi-animation-4" stroke-dasharray="737 1474" stroke-linecap="round"></path>
    
      <clipPath id="make-me-a-hanzi-clip-9">
        <path d="M 576 207 Q 577 208 579 208 Q 673 259 720 277 Q 739 280 735 292 Q 731 308 714 330 Q 696 351 674 356 Q 658 357 657 337 Q 657 316 562 218 C 541 196 549 195 576 207 Z"></path>
      </clipPath>
      <path clip-path="url(#make-me-a-hanzi-clip-9)" d="M 723 289 L 683 302 L 575 214" fill="none" id="make-me-a-hanzi-animation-9" stroke-dasharray="309 618" stroke-linecap="round"></path>
    
      <clipPath id="make-me-a-hanzi-clip-10">
        <path d="M 461 293 Q 457 315 429 333 Q 411 343 400 345 Q 391 345 391 333 Q 385 261 245 160 Q 242 160 240 157 Q 200 129 104 79 Q 95 76 104 71 Q 170 64 301 146 Q 307 153 336 171 L 371 199 Q 441 263 450 268 C 466 280 466 280 461 293 Z"></path>
      </clipPath>
      <path clip-path="url(#make-me-a-hanzi-clip-10)" d="M 403 333 L 420 292 L 364 226 L 247 136 L 162 93 L 109 75" fill="none" id="make-me-a-hanzi-animation-7" stroke-dasharray="558 1116" stroke-linecap="round"></path>
    
  </g>
</svg>

**Comment by skishore** [comment]
The SVGs are just derived data from the base data in the tool branch. The tool will automatically detect any other characters that include this one as a component, so that's a more robust fix. I'll have time for these edits over the weekend.

**Comment by skishore** [comment]
Fixed in 618dbab8a8ddefb958763c8b4afbaa741a4460de.
