### ISSUE TITLE
Stroke order error in 瑤謠遙

### ISSUE THREAD

**Issue by parsimonhi** [skishore/makemeahanzi#53]
Wrong stroke order in the 𠂊⺀part of 瑤謠遙 and possibly in other characters that contain the same component.

搖 and 鷂 have already the correct stroke order.

**Comment by skishore** [comment]
Thanks for the catch! I'll get to this issue and the other data bugs over the weekend.

**Comment by skishore** [comment]
The root of the issue here was that the simplified characters use a slightly different version of this component: 䍃. When detecting stroke order in the traditional characters, the automation matches against that component and gets it wrong. Fixed 6 errors.
