### ISSUE TITLE
这个字体是什么字体呢？

### ISSUE THREAD

**Issue by fndppx** [skishore/makemeahanzi#63]
这个字体是什么字体呢？

**Comment by fndppx** [comment]
Arphic PL KaitiM GB 是这个字体么？能商业用么亲？

**Comment by skishore** [comment]
My apologies - I don't actually know Chinese, but I gather that you're asking about the font and whether it can be used commercially.

There are two fonts being used here: Arphic PL KaitiM GB and Arphic PL UKai. The second is a variant of the first one with many more glyphs, but not all the new glyphs are as high-quality as the original.

These fonts and this dataset are all licensed under the original Arphic Public License from 1999 (hence, "Arphic PL"). That license is a copy-left license which allows redistribution and modification as long as the data and license are made available along with whatever you're redistributing them with, and as long as any modifications are also licensed under the same terms. [You can see the full text of the license here.](https://github.com/skishore/makemeahanzi/tree/master/APL)

Note that in 2000 Arphic Technologies has created a new license with more restricted terms, which is also called the Arphic Public License. Make Me a Hanzi only uses fonts licensed under the old one.

**Comment by rodrigo-morales-1** [comment]
For the record, some Arphic fonts can be downloaded in https://deb.debian.org/debian/pool/main/f/ . In that URL, I found these directories:

```
[DIR]	fonts-arphic-bkai00mp/	2023-04-28 14:17 	-
[DIR]	fonts-arphic-bsmi00lp/	2023-03-29 08:22 	-
[DIR]	fonts-arphic-gbsn00lp/	2023-03-29 02:21 	-
[DIR]	fonts-arphic-gkai00mp/	2023-03-29 02:21 	-
[DIR]	fonts-arphic-ukai/	2019-11-01 22:19 	-
[DIR]	fonts-arphic-uming/	2023-04-28 02:17 	-
```
