### ISSUE TITLE
Does the business need to charge

### ISSUE THREAD

**Issue by fndppx** [skishore/makemeahanzi#66]
What font does this use? Does the business need to charge? I am currently using dictionary.txt and the following method. Is this two fonts? Is it the same thing

![image](https://user-images.githubusercontent.com/7971897/50532224-56524700-0b51-11e9-8cc5-fa53719fab26.png)

**Comment by skishore** [comment]
Hanzi Writer is by @chanind, so this information is second-hand, but the license is MIT, so no, I would not expect that you have to charge. See: https://github.com/chanind/hanzi-writer#license
