### ISSUE TITLE
How to use this data for character recognition from drawing point as in demo page?

### ISSUE THREAD

**Issue by ndquangr** [skishore/makemeahanzi#68]
Could you please tell me how to use this data for character recognition from drawing point as in demo page? Thank you!

**Comment by skishore** [comment]
Instantiate a [Matcher object](https://github.com/skishore/makemeahanzi/blob/demo/lib/matcher.js#L139) with the (character, medians) data. Then, take the user's raw stroke inputs, call "Matcher.preprocess" to do some light cleanup on them, and then pass the result to "Matcher.match".
