### ISSUE TITLE
Calligraphy-free stroke data?

### ISSUE THREAD

**Issue by DonaldTsang** [skishore/makemeahanzi#76]
https://github.com/KanjiVG/kanjivg is a great resource for Kanji, but as their name suggests they only support Japanese Kanji and does not include Traditional Chinese or Simplified Chinese.

Is it possible to add support for that, as I would like to recreate http://blog.otoro.net/2015/12/28/recurrent-net-dreams-up-fake-chinese-characters-in-vector-format-with-tensorflow/ and http://otoro.net/kanji/ ?

Also asking the same question at https://github.com/KanjiVG/kanjivg/issues/187

**Comment by skishore** [comment]
The "medians" field in the dictionary.txt rows is my attempt to extract the "core" of each stroke.

It's not perfect, but it's accurate enough that handwriting recognition algorithms using that field work well.

**Comment by DonaldTsang** [comment]
Thanks!
