### ISSUE TITLE
background lines

### ISSUE THREAD

**Issue by matthewmorrone1** [skishore/makemeahanzi#8]
is there any easy way to get rid of the background lines?

**Comment by matthewmorrone1** [comment]
just kidding. can't delete this now

**Comment by skishore** [comment]
For anyone else with the same question, here are some options:

- Apply a CSS rule that hides the lines
- Edit the [code](https://github.com/skishore/makemeahanzi/blob/tool/lib/animation.js) and/or [template](https://github.com/skishore/makemeahanzi/blob/tool/lib/animation.html) I used to generate these graphics and re-run it
- Write a script that edits the SVG files as needed
