### ISSUE TITLE
Bounding box for characters on canvas

### ISSUE THREAD

**Issue by dhowe** [skishore/makemeahanzi#82]
Greetings. I'm drawing characters, stroke-by-stroke on canvas2d in the browser. How do I get the bounding box for the character?

**Comment by skishore** [comment]
From the README:

**strokes:** List of SVG path data for each stroke of this character, ordered by proper stroke order. Each stroke is laid out on a 1024x1024 size coordinate system where:
 - The upper-left corner is at position (0, 900).
 - The lower-right corner is at position (1024, -124).

Note that the y-axes DECREASES as you move downwards, which is strage! To display these paths properly, you should hide render them as follows:

```
<svg viewBox="0 0 1024 1024">
  <g transform="scale(1, -1) translate(0, -900)">
    <path d="STROKE[0] DATA GOES HERE"></path>
    <path d="STROKE[1] DATA GOES HERE"></path>
    ...
  </g>
</svg>
```
