### ISSUE TITLE
How to generate alphabet(A-Z, a-z) and Arabic numerals(0-9) animated svg files.

### ISSUE THREAD

**Issue by donly** [skishore/makemeahanzi#84]
I can running according to https://github.com/skishore/makemeahanzi/issues/37, still finding a way to add alphabet and numbers.

and ,it seem the same requirement with https://github.com/skishore/makemeahanzi/issues/58.

**Comment by donly** [comment]
Oh, I know how to add new characters, just input to the url as a parameter, very nice.

**Comment by hugolpz** [comment]
Not clear. Please when coming over a bottlenect share better instruction so the next visitor can follow your path smoothly. 👍🏼

**Comment by zhangquanchen** [comment]
Hi, has any body generated the alphabet(A-Z, a-z) and Arabic numerals(0-9)? thanks!
