### ISSUE TITLE
makemeahanzi.herokuapp.com doesn't work

### ISSUE THREAD

**Issue by orecchionebruno** [skishore/makemeahanzi#86]
hello, I see that makemeahanzi.herokuapp.com doesn't work, may you please fix it?

thanks

this is the error that appears:

_Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail_

**Comment by skishore** [comment]
I had to bring down the website for a short time to migrate to a new database. It should be working now.
