### ISSUE TITLE
mapping between images and data, plus

### ISSUE THREAD

**Issue by matthewmorrone1** [skishore/makemeahanzi#9]
is there any way to associate the character data with their corresponding svg? are the svgs named in the same order as they appear in the data files?

**Comment by Bliss00** [comment]
Corresponding SVG files are named by unsigned unichar of the associated characters

**Comment by skishore** [comment]
That's right. I would have named them after the actual characters, but some filesystems (like my Android phone's) don't behave well with Unicode file names.
